//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresetEditor.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresetEditor.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 常规操作 的本地化字符串。
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中项，进行增删改等操作 的本地化字符串。
        /// </summary>
        internal static string ActionsDesc {
            get {
                return ResourceManager.GetString("ActionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加行 的本地化字符串。
        /// </summary>
        internal static string AddLIneRemind {
            get {
                return ResourceManager.GetString("AddLIneRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️严格区分大小写 的本地化字符串。
        /// </summary>
        internal static string CaseSenstive {
            get {
                return ResourceManager.GetString("CaseSenstive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约定: 统一将分组配置放到节点的UserControls下 的本地化字符串。
        /// </summary>
        internal static string Convention {
            get {
                return ResourceManager.GetString("Convention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪表盘 的本地化字符串。
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪表盘 视图 的本地化字符串。
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️确认要删除最后一行么? 的本地化字符串。
        /// </summary>
        internal static string DeleteLIneContent {
            get {
                return ResourceManager.GetString("DeleteLIneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        internal static string DeleteLineRemind {
            get {
                return ResourceManager.GetString("DeleteLineRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️确认删除选中的项么？ 的本地化字符串。
        /// </summary>
        internal static string DeleteRemind {
            get {
                return ResourceManager.GetString("DeleteRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出配置 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件路径:  的本地化字符串。
        /// </summary>
        internal static string ExportFilePath {
            get {
                return ResourceManager.GetString("ExportFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出配置成功 的本地化字符串。
        /// </summary>
        internal static string ExportFilePathRemind {
            get {
                return ResourceManager.GetString("ExportFilePathRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局导出 的本地化字符串。
        /// </summary>
        internal static string ExportGlobal {
            get {
                return ResourceManager.GetString("ExportGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前公开参数和分组配置需要分别导出，然后复制粘贴到模板中再生效，后续计划直接导出整个模板文件 的本地化字符串。
        /// </summary>
        internal static string ExportGlobalDesc {
            get {
                return ResourceManager.GetString("ExportGlobalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取 的本地化字符串。
        /// </summary>
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果已有分组配置，可以进行提取 的本地化字符串。
        /// </summary>
        internal static string ExtractState {
            get {
                return ResourceManager.GetString("ExtractState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选取文件 的本地化字符串。
        /// </summary>
        internal static string FileSelector {
            get {
                return ResourceManager.GetString("FileSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️分组名重复，添加失败 的本地化字符串。
        /// </summary>
        internal static string GroupDumplicateRemind {
            get {
                return ResourceManager.GetString("GroupDumplicateRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组节点名 的本地化字符串。
        /// </summary>
        internal static string GroupNode {
            get {
                return ResourceManager.GetString("GroupNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️分组节点名不能为空 的本地化字符串。
        /// </summary>
        internal static string GroupNodeEmptyRemind {
            get {
                return ResourceManager.GetString("GroupNodeEmptyRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请先填写分组源页中的分组节点名，之后才能进行匹配 的本地化字符串。
        /// </summary>
        internal static string GroupNodeRemind {
            get {
                return ResourceManager.GetString("GroupNodeRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组节点类型 的本地化字符串。
        /// </summary>
        internal static string GroupNodeType {
            get {
                return ResourceManager.GetString("GroupNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️分组节点类型不能为空 的本地化字符串。
        /// </summary>
        internal static string GroupNodeTypeEmptyRemind {
            get {
                return ResourceManager.GetString("GroupNodeTypeEmptyRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计分组 数量 的本地化字符串。
        /// </summary>
        internal static string GroupsCounter {
            get {
                return ResourceManager.GetString("GroupsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请确保分组源页中的分组配置项不为空 的本地化字符串。
        /// </summary>
        internal static string GroupsEmptyRemind {
            get {
                return ResourceManager.GetString("GroupsEmptyRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记分组 的本地化字符串。
        /// </summary>
        internal static string GroupsMarker {
            get {
                return ResourceManager.GetString("GroupsMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组源 的本地化字符串。
        /// </summary>
        internal static string GroupSource {
            get {
                return ResourceManager.GetString("GroupSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即时预览 的本地化字符串。
        /// </summary>
        internal static string LivePreview {
            get {
                return ResourceManager.GetString("LivePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结合公开参数和分组配置，生成与模板Inspector面板一致的分组分页的布局设置，带来更直观的预览效果 的本地化字符串。
        /// </summary>
        internal static string LivePreviewDesc {
            get {
                return ResourceManager.GetString("LivePreviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始加载 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️初始加载公开参数(现有的配置和操作都将被重置) 的本地化字符串。
        /// </summary>
        internal static string LoadRemind {
            get {
                return ResourceManager.GetString("LoadRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多项拖放 的本地化字符串。
        /// </summary>
        internal static string MultiDragDrop {
            get {
                return ResourceManager.GetString("MultiDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前只支持单项拖放，虽然有批量移动的功能，但是仍然多有不便，后续要针对多项拖放功能提供支持 的本地化字符串。
        /// </summary>
        internal static string MultiDragDropDesc {
            get {
                return ResourceManager.GetString("MultiDragDropDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计分页 数量 的本地化字符串。
        /// </summary>
        internal static string PagesCounter {
            get {
                return ResourceManager.GetString("PagesCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记分页 的本地化字符串。
        /// </summary>
        internal static string PagesMarker {
            get {
                return ResourceManager.GetString("PagesMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计公开参数 数量 的本地化字符串。
        /// </summary>
        internal static string ParasCounter {
            get {
                return ResourceManager.GetString("ParasCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️当前没有任何公开参数项 的本地化字符串。
        /// </summary>
        internal static string ParasEmptyRemind {
            get {
                return ResourceManager.GetString("ParasEmptyRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未来计划 的本地化字符串。
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️此功能当前尚处于preview阶段，未经过完全测试，请谨慎使用 的本地化字符串。
        /// </summary>
        internal static string PreviewRemind {
            get {
                return ResourceManager.GetString("PreviewRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实现可视化界面配置达芬奇模板的分组与分页 的本地化字符串。
        /// </summary>
        internal static string ProjectSubject {
            get {
                return ResourceManager.GetString("ProjectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开参数 的本地化字符串。
        /// </summary>
        internal static string PublishedParas {
            get {
                return ResourceManager.GetString("PublishedParas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒 的本地化字符串。
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string ReOrder {
            get {
                return ResourceManager.GetString("ReOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请选择需要移动的项 的本地化字符串。
        /// </summary>
        internal static string ReOrderRemind {
            get {
                return ResourceManager.GetString("ReOrderRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动目标:  的本地化字符串。
        /// </summary>
        internal static string ReOrderTarget {
            get {
                return ResourceManager.GetString("ReOrderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请选择需要移动到的目标项 的本地化字符串。
        /// </summary>
        internal static string ReorderTargetRemind {
            get {
                return ResourceManager.GetString("ReorderTargetRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索内容 的本地化字符串。
        /// </summary>
        internal static string SearchContent {
            get {
                return ResourceManager.GetString("SearchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请先填写搜索内容 的本地化字符串。
        /// </summary>
        internal static string SearchContentRemind {
            get {
                return ResourceManager.GetString("SearchContentRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类别 的本地化字符串。
        /// </summary>
        internal static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请先选择搜索类型 的本地化字符串。
        /// </summary>
        internal static string SearchTypeRemind {
            get {
                return ResourceManager.GetString("SearchTypeRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中项 的本地化字符串。
        /// </summary>
        internal static string SelectedItem {
            get {
                return ResourceManager.GetString("SelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️ 请先选中一项再进行操作 的本地化字符串。
        /// </summary>
        internal static string SelectItemRemind {
            get {
                return ResourceManager.GetString("SelectItemRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️ 请先选中一项或多项再进行操作 的本地化字符串。
        /// </summary>
        internal static string SelectItemsRemind {
            get {
                return ResourceManager.GetString("SelectItemsRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标位置 的本地化字符串。
        /// </summary>
        internal static string SelectTargetItem {
            get {
                return ResourceManager.GetString("SelectTargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步分组 的本地化字符串。
        /// </summary>
        internal static string SyncGroups {
            get {
                return ResourceManager.GetString("SyncGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️同步只会添加公开参数中不存在的分组配置项！确认要同步么? 的本地化字符串。
        /// </summary>
        internal static string SyncGroupsRemind {
            get {
                return ResourceManager.GetString("SyncGroupsRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板文件路径:  的本地化字符串。
        /// </summary>
        internal static string TemplateFile {
            get {
                return ResourceManager.GetString("TemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚠️请先导入正确的模板文件 的本地化字符串。
        /// </summary>
        internal static string TemplateFileRemind {
            get {
                return ResourceManager.GetString("TemplateFileRemind", resourceCulture);
            }
        }
    }
}
