//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresetEditor.Resources.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PresetEditor.Resources.Languages.AppResources_en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        internal static string FileSelector {
            get {
                return ResourceManager.GetString("FileSelector", resourceCulture);
            }
        }
        
        internal static string TemplateFile {
            get {
                return ResourceManager.GetString("TemplateFile", resourceCulture);
            }
        }
        
        internal static string ParasCounter {
            get {
                return ResourceManager.GetString("ParasCounter", resourceCulture);
            }
        }
        
        internal static string GroupsCounter {
            get {
                return ResourceManager.GetString("GroupsCounter", resourceCulture);
            }
        }
        
        internal static string PagesCounter {
            get {
                return ResourceManager.GetString("PagesCounter", resourceCulture);
            }
        }
        
        internal static string PublishedParas {
            get {
                return ResourceManager.GetString("PublishedParas", resourceCulture);
            }
        }
        
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        internal static string ExportFilePath {
            get {
                return ResourceManager.GetString("ExportFilePath", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ActionsDesc {
            get {
                return ResourceManager.GetString("ActionsDesc", resourceCulture);
            }
        }
        
        internal static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        internal static string SearchContent {
            get {
                return ResourceManager.GetString("SearchContent", resourceCulture);
            }
        }
        
        internal static string GroupsMarker {
            get {
                return ResourceManager.GetString("GroupsMarker", resourceCulture);
            }
        }
        
        internal static string PagesMarker {
            get {
                return ResourceManager.GetString("PagesMarker", resourceCulture);
            }
        }
        
        internal static string SyncGroups {
            get {
                return ResourceManager.GetString("SyncGroups", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string ReOrderTarget {
            get {
                return ResourceManager.GetString("ReOrderTarget", resourceCulture);
            }
        }
        
        internal static string SelectTargetItem {
            get {
                return ResourceManager.GetString("SelectTargetItem", resourceCulture);
            }
        }
        
        internal static string ReOrder {
            get {
                return ResourceManager.GetString("ReOrder", resourceCulture);
            }
        }
        
        internal static string GroupSource {
            get {
                return ResourceManager.GetString("GroupSource", resourceCulture);
            }
        }
        
        internal static string Convention {
            get {
                return ResourceManager.GetString("Convention", resourceCulture);
            }
        }
        
        internal static string ExtractState {
            get {
                return ResourceManager.GetString("ExtractState", resourceCulture);
            }
        }
        
        internal static string GroupNode {
            get {
                return ResourceManager.GetString("GroupNode", resourceCulture);
            }
        }
        
        internal static string GroupNodeType {
            get {
                return ResourceManager.GetString("GroupNodeType", resourceCulture);
            }
        }
        
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string ProjectSubject {
            get {
                return ResourceManager.GetString("ProjectSubject", resourceCulture);
            }
        }
        
        internal static string MultiDragDrop {
            get {
                return ResourceManager.GetString("MultiDragDrop", resourceCulture);
            }
        }
        
        internal static string ExportGlobal {
            get {
                return ResourceManager.GetString("ExportGlobal", resourceCulture);
            }
        }
        
        internal static string LivePreview {
            get {
                return ResourceManager.GetString("LivePreview", resourceCulture);
            }
        }
        
        internal static string MultiDragDropDesc {
            get {
                return ResourceManager.GetString("MultiDragDropDesc", resourceCulture);
            }
        }
        
        internal static string ExportGlobalDesc {
            get {
                return ResourceManager.GetString("ExportGlobalDesc", resourceCulture);
            }
        }
        
        internal static string LivePreviewDesc {
            get {
                return ResourceManager.GetString("LivePreviewDesc", resourceCulture);
            }
        }
        
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        internal static string GroupNodeRemind {
            get {
                return ResourceManager.GetString("GroupNodeRemind", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string SearchTypeRemind {
            get {
                return ResourceManager.GetString("SearchTypeRemind", resourceCulture);
            }
        }
        
        internal static string SearchContentRemind {
            get {
                return ResourceManager.GetString("SearchContentRemind", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        internal static string ParasEmptyRemind {
            get {
                return ResourceManager.GetString("ParasEmptyRemind", resourceCulture);
            }
        }
        
        internal static string ExportFilePathRemind {
            get {
                return ResourceManager.GetString("ExportFilePathRemind", resourceCulture);
            }
        }
        
        internal static string SyncGroupsRemind {
            get {
                return ResourceManager.GetString("SyncGroupsRemind", resourceCulture);
            }
        }
        
        internal static string GroupsEmptyRemind {
            get {
                return ResourceManager.GetString("GroupsEmptyRemind", resourceCulture);
            }
        }
        
        internal static string SelectItemRemind {
            get {
                return ResourceManager.GetString("SelectItemRemind", resourceCulture);
            }
        }
        
        internal static string SelectItemsRemind {
            get {
                return ResourceManager.GetString("SelectItemsRemind", resourceCulture);
            }
        }
        
        internal static string ReOrderRemind {
            get {
                return ResourceManager.GetString("ReOrderRemind", resourceCulture);
            }
        }
        
        internal static string ReorderTargetRemind {
            get {
                return ResourceManager.GetString("ReorderTargetRemind", resourceCulture);
            }
        }
        
        internal static string TemplateFileRemind {
            get {
                return ResourceManager.GetString("TemplateFileRemind", resourceCulture);
            }
        }
        
        internal static string LoadRemind {
            get {
                return ResourceManager.GetString("LoadRemind", resourceCulture);
            }
        }
        
        internal static string GroupNodeEmptyRemind {
            get {
                return ResourceManager.GetString("GroupNodeEmptyRemind", resourceCulture);
            }
        }
        
        internal static string GroupNodeTypeEmptyRemind {
            get {
                return ResourceManager.GetString("GroupNodeTypeEmptyRemind", resourceCulture);
            }
        }
        
        internal static string DeleteRemind {
            get {
                return ResourceManager.GetString("DeleteRemind", resourceCulture);
            }
        }
        
        internal static string GroupDumplicateRemind {
            get {
                return ResourceManager.GetString("GroupDumplicateRemind", resourceCulture);
            }
        }
        
        internal static string AddLIneRemind {
            get {
                return ResourceManager.GetString("AddLIneRemind", resourceCulture);
            }
        }
        
        internal static string DeleteLineRemind {
            get {
                return ResourceManager.GetString("DeleteLineRemind", resourceCulture);
            }
        }
        
        internal static string DeleteLIneContent {
            get {
                return ResourceManager.GetString("DeleteLIneContent", resourceCulture);
            }
        }
    }
}
