name: Build MAUI App (Windows Only For Now)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release 版本号（例：v1.0.0）'
        required: true

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: DavinciPreset/src/PresetEditor
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 重要：拉取完整历史，这样才能打 tag

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push Git tag
        run: |
          TAG=${{ github.event.inputs.version }}
          # 检查 tag 是否已经存在
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "❌ Tag $TAG already exists"
            exit 1
          fi
          git tag $TAG
          git push origin $TAG
          echo "✅ Tag $TAG created and pushed."

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows App
        run: dotnet publish PresetEditor.csproj -c Release -f net9.0-windows10.0.19041.0

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            **/bin/Release/net9.0-windows10.0.19041.0/win-x64/publish/**

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET SDK
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 9.0.x

  #     - name: Install MAUI workload
  #       run: dotnet workload install maui

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     # 可以在这里加签名参数 CodesignKey 等
  #     - name: Publish MacCatalyst App
  #       run: dotnet publish PresetEditor.csproj -c Release -f net9.0-maccatalyst

  #     - name: Upload MacOS Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-release
  #         path: |
  #           **/bin/Release/net9.0-maccatalyst/maccatalyst-arm64/publish/**
  
  release:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: windows-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}   # ← 手动指定 tag 名
          files: |
            windows-release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
